CREATE TABLE `MEMBER` (
	`NO`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`ID`	TEXT NOT NULL UNIQUE,
	`PWD`	TEXT,
	`NAME`	TEXT,
	`EMAIL`	TEXT UNIQUE,
	`SCORE`	TEXT,
	`CHARACTER`	TEXT,
	`STAGE1CLEAR`	INTEGER,
	`STAGE1_1CLEAR`	INTEGER,
	`STAGE1_2CLEAR`	INTEGER,
	`STAGE1_3CLEAR`	INTEGER,
	`STAGE2CLEAR`	INTEGER,
	`STAGE2_1CLEAR`	INTEGER,
	`STAGE2_2CLEAR`	INTEGER,
	`STAGE2_3CLEAR`	INTEGER,
	`STAGE3CLEAR`	INTEGER
);